# Generated by Django 2.2.28 on 2024-03-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CriticCorner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
    ]
