# Generated by Django 2.2.28 on 2024-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriticCorner', '0002_auto_20240304_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='test_media/R.jpeg', upload_to='media/pfps'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='media/posters'),
        ),
    ]
