# Generated by Django 2.2.28 on 2024-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriticCorner', '0003_auto_20240306_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
