# Generated by Django 2.2.28 on 2024-03-14 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriticCorner', '0004_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='api_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=1000),
        ),
    ]
